[log]
level = "info"

[location]
longitude = "0.0"
latitude = "0.0"
radius = "520"
file = "/tmp/alerti3"

[dbpg]
dburl="host.org.local"
dbport=5432
dbuser="hazards"
dbname="wobbly"
dbpassword="xxxx"

[color]
green="#00FF66"
yellow="#FFFF66"
orange="#FFCC33"
red="#CC3366"

[nasa]
mapkey="xxxx"
coordbox="-180,-80,180,80"
#coordbox="30,-20,60,40"
